name: 'Test Control Plane'
description: 'Runs tests on the Pinecone control plane'

inputs:
  test_suite:
    description: 'The type of the index (serverless, pod)'
    required: true
    default: 'serverless'
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.9'
  metric:
    description: 'The metric of the index'
    required: true
  dimension:
    description: 'The dimension of the index'
    required: true
  spec:
    description: 'The deploy spec of the index'
    required: true
  use_grpc:
    description: 'Whether to use gRPC or REST'
    required: true
  freshness_timeout_seconds:
    description: 'The number of seconds to wait for the index to become fresh'
    required: false
    default: '60'
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
      with:
        include_grpc: ${{ inputs.use_grpc }}
        include_dev: 'true'

    - name: Run tests
      id: data-plane-tests
      shell: bash
      run: poetry run pytest tests/integration/control/${{ inputs.test_suite }}
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        USE_GRPC: ${{ inputs.use_grpc }}
        METRIC: ${{ inputs.metric }}
        DIMENSION: ${{ inputs.dimension }}
        SPEC: ${{ inputs.spec }}
        FRESHNESS_TIMEOUT_SECONDS: ${{ inputs.freshness_timeout_seconds }}
        GITHUB_BUILD_NUMBER: '${{ github.run_number }}-p-${{ matrix.testConfig.python-version}}'