name: 'PyPI Release: Pre-Release (pinecone)'

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build (branch name or SHA)'
        required: true
        type: string
        default: 'main'
      releaseLevel:
        description: 'Release level'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'patch' # bug fixes
          - 'minor' # new features, backwards compatible
          - 'major' # breaking changes
      prereleaseSuffix:
        description: 'Suffix to add onto the new version number in order to mark it as a prerelease'
        required: true
        type: string
        default: 'rc1'
      skipTests:
        description: 'Skip running tests'
        required: false
        type: boolean
        default: false

jobs:
  unit-tests:
    if: ${{ inputs.skipTests == 'true' }}
    uses: './.github/workflows/testing-unit.yaml'
    secrets: inherit
  integration-tests:
      if: ${{ inputs.skipTests == 'true' }}
      uses: './.github/workflows/testing-integration.yaml'
      secrets: inherit
  dependency-tests:
    if: ${{ inputs.skipTests == 'true' }}
    uses: './.github/workflows/testing-dependency.yaml'
    secrets: inherit

  pypi:
    uses: './.github/workflows/publish-to-pypi.yaml'
    needs: 
      - unit-tests
      - integration-tests
      - dependency-tests
    with:
      isPrerelease: true
      ref: ${{ inputs.ref }}
      releaseLevel: ${{ inputs.releaseLevel }}
      prereleaseSuffix: ${{ inputs.prereleaseSuffix }}
      TWINE_REPOSITORY: 'pypi'
    secrets:
      PYPI_USERNAME: __token__
      PYPI_PASSWORD: ${{ secrets.PROD_PYPI_PUBLISH_TOKEN }}
