name: Pull-request CI

on: pull_request

jobs:
  run-tests:
    name: Run tests
    runs-on: self-hosted
    if: ${{ !contains(github.head_ref, 'docs') }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Run tests
      run: make tests

    - name: Build Python client
      run: make package

    - name: Build docs
      run: make docs
