name: Pypi

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build (branch name or SHA)'
        required: true
        type: string
        default: 'main' 
      releaseLevel:
        description: 'Release level'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'patch' # bug fixes
          - 'minor' # new features, backwards compatible
          - 'major' # breaking changes

env:
  PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

jobs:

  pypi:
    timeout-minutes: 30
    name: pypi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Need full history and tags to compute list of commits in release
        ref: ${{ github.event.inputs.ref }}

    - name: Set up Git
      run: |
        git config --global user.name "Pinecone CI"
        git config --global user.email "clients@pinecone.io"

    - name: Bump version
      id: bump
      uses: './.github/actions/bump-version'
      with:
        versionFile: pinecone/__version__ 
        bumpType: ${{ github.event.inputs.releaseLevel }}

    - name: Commit and tag version bump
      id: tag_release
      run: |
        git add pinecone/__version__
        newVersionTag="${{ steps.bump.outputs.VERSION_TAG }}"
        git commit -m "Bump version to $newVersionTag"
        git tag -a $newVersionTag -m "Release $newVersionTag"

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Set Python client production environment
      run: make set-production

    - name: Build Python client
      run: make package

    - name: Upload Python client to Pypi
      run: make upload

    - name: Push changes and tags
      run: |
        git push --follow-tags